### ISSUE TITLE
Configuring Codeclimate

### ISSUE THREAD

**Issue by cyri113** [RnDAO/tc-operation#29]
- [x] Create an account on https://codeclimate.com/ (use your Github)
- [x] Add the **RnDAO** organisation
- [x] Add the following repositories:

| repo |
| ---- |
| tc-uiComms|
| tc-serverComms|
| tc-DAOlytics |
| tc-botComms |

Documentation:
- https://docs.codeclimate.com/docs/getting-started-with-code-climate
- https://codeclimate.com/quality/pricing (should be free, even for DAOlytics if you only have Amin, Ene, and myself)

**Comment by daniel-ospina** [comment]
requires demo to create account. I fIlled the form
